channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python>=3.10,<3.12
  - plotly>=5.0.0,<6.0.0
  - py-xgboost>=2.0.0,<3.0.0
  - scikit-learn>=0.21.2,<2.0.0
  - pandas>=2.0.0,<3.0.0
  - catboost>=1.0.0,<2.0.0
  - lightgbm>=3.0.0,<4.0.0
  - category_encoders>=2.2.0,<3.0.0
  - ipywidgets>=7.6.0,<9.0.0
  - jupyterlab>=3.0.0,<4.0.0
  - openpyxl>=3.0.0,<4.0.0
  - pyarrow>=10.0.1,<11.0.0
  - lxml>=5.2.1, <6.0.0
  - numpy>=1.24.0,<2.0.0
  - scipy>=1.10.0,<2.0.0
  - tqdm>=4.0.0,<5.0.0
  - fastparquet>=2024.2.0, <2024.5.0
  - matplotlib>=3.7.0,<4.0.0
  - humanize>=4.0.0,<5.0.0
  - optuna>=3.4.0,<4.0.0
  - numba>=0.53.0,<1.0.0
  - networkx>=3.1.0,<4.0.0
  - holidays>=0.13.0,<1.0.0
  - seaborn>=0.13.2,<1.0.0
  - statsmodels>=0.14.0,<0.15.0
  - statsforecast>=1.7.3,<2.0.0
  - neuralforecast>=1.7.2,<2.0.0
  - mlforecast>=0.13.1,<1.0.0
  - pytorch-lightning>=2.0.0,<3.0.0
  - pip>=21.0.0,<23.0.0
  - pip:
    - kaggle>=1.5.2,<2.0.0
    - missingno>=0.5.0,<1.0.0
    - window_ops>=0.0.15,<1.0.0
    - pymannkendall>=1.4.3,<2.0.0
    - tsfel>=0.1.7,<1.0.0
    - rich>=13.0.0,<14.0.0
    - pytorch_tabular[all]>=1.1.0,<2.0.0
    - omegaconf>=2.0.0,<3.0.0
    - tensor-sensor[torch]>=1.0.0,<2.0.0
    - pytorch_optimizer>=3.0.0,<4.0.0
    - kaleido==0.1.0.post1
    - datasetsforecast>=0.0.8, <1.0.0
    - xlrd >=2.0.1, <3.0.0